"""
Download the web fonts from Google and serve them from our own domain.

Why bother: loading them from fonts.googleapis.com costs a DNS lookup, a TLS
handshake, a render-blocking stylesheet and then the font files themselves,
all before any text can paint. On the mobile connections most ad traffic
arrives on that is several hundred milliseconds of blank text, and Google
scores landing page speed as part of Quality Score.

It also matters for the privacy position these pages take. A request to
Google Fonts happens on page load, before a visitor has consented to
anything. Self-hosting means the page really does make no third-party
requests until the tracking IDs are configured, which is what the privacy
policy describes.

Only the latin and latin-ext subsets are kept. latin-ext is needed for the
accented characters in names such as Universidade Catolica Timorense.

    python tools/fetch-fonts.py

Writes assets/fonts/*.woff2 and css/fonts.css. Re-run only if the font
stack in the design changes.
"""

import os
import re
import urllib.request

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Sora:wght@400;600;700;800"
    "&family=Manrope:wght@400;500;600;700"
    "&family=Space+Mono:wght@700"
    "&display=swap"
)

# Asking as a modern browser is what makes Google serve woff2 rather than
# an older, much larger format.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP_SUBSETS = {"latin", "latin-ext"}
FONT_DIR = "assets/fonts"
OUT_CSS = "css/fonts.css"


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = get(CSS_URL)

    # Each @font-face is preceded by a /* subset */ comment.
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)

    kept, seen, total = [], set(), 0
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue

        url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not url:
            continue
        url = url.group(1)

        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"

        if name not in seen:
            path = os.path.join(FONT_DIR, name)
            data = get(url, binary=True)
            with open(path, "wb") as fh:
                fh.write(data)
            seen.add(name)
            total += len(data)
            print(f"  {name:38s} {len(data)/1024:6.1f} KB")

        kept.append(block.replace(url, f"/assets/fonts/{name}"))

    header = (
        "/* Self-hosted web fonts. Generated by tools/fetch-fonts.py.\n"
        "   Served from our own domain so no third-party request is needed\n"
        "   before the page can paint. Do not edit by hand. */\n\n"
    )
    with open(OUT_CSS, "w", encoding="utf-8") as fh:
        fh.write(header + "\n".join(kept) + "\n")

    print(f"\n{len(kept)} @font-face rules -> {OUT_CSS}")
    print(f"{len(seen)} files, {total/1024:.0f} KB total")


if __name__ == "__main__":
    main()
